import { COLORS, images } from "../constants";
export { colorsData, iconsData, currencyData };

const colorsData = [
    COLORS.lightblue,
    COLORS.lightcoral,
    COLORS.lightcyan,
    COLORS.lightgoldenrodyellow,
    COLORS.lightgray,
    COLORS.lightgreen,
    COLORS.lightpink,
    COLORS.lightsalmon,
    COLORS.lightseagreen,
    COLORS.lightskyblue,
    COLORS.lightsteelblue,
    COLORS.lightyellow,
];

const iconsData = [
    images.beauty,
    images.bills,
    images.car,
    images.charity,
    images.cocktail,
    images.computer,
    images.education,
    images.entertainment,
    images.finance,
    images.food,
    images.fuel,
    images.gift,
    images.groceries,
    images.healtcare,
    images.holidays,
    images.home,
    images.income,
    images.investment,
    images.kids,
    images.loans,
    images.other,
    images.restaurant,
    images.shopping,
    images.shoppingBag,
    images.sport,
    images.taxes,
    images.transport,
    images.travel,
    images.tshirt,
    images.work,
];

const currencyData = [
    {
        id: 1,
        country: "Afghanistan",
        currenciesCode: "AFN",
        currenciesName: "Afghan afghani",
        flag: "https://www.countryflags.io/AF/flat/64.png",
    },
    {
        id: 2,
        country: "Åland Islands",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/AX/flat/64.png",
    },
    {
        id: 3,
        country: "Albania",
        currenciesCode: "ALL",
        currenciesName: "Albanian lek",
        flag: "https://www.countryflags.io/AL/flat/64.png",
    },
    {
        id: 4,
        country: "Algeria",
        currenciesCode: "DZD",
        currenciesName: "Algerian dinar",
        flag: "https://www.countryflags.io/DZ/flat/64.png",
    },
    {
        id: 5,
        country: "American Samoa",
        currenciesCode: "USD",
        currenciesName: "United State Dollar",
        flag: "https://www.countryflags.io/AS/flat/64.png",
    },
    {
        id: 6,
        country: "Andorra",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/AD/flat/64.png",
    },
    {
        id: 7,
        country: "Angola",
        currenciesCode: "AOA",
        currenciesName: "Angolan kwanza",
        flag: "https://www.countryflags.io/AO/flat/64.png",
    },
    {
        id: 8,
        country: "Anguilla",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/AI/flat/64.png",
    },
    {
        id: 9,
        country: "Antarctica",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/AQ/flat/64.png",
    },
    {
        id: 10,
        country: "Antigua and Barbuda",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/AG/flat/64.png",
    },
    {
        id: 11,
        country: "Argentina",
        currenciesCode: "ARS",
        currenciesName: "Argentine peso",
        flag: "https://www.countryflags.io/AR/flat/64.png",
    },
    {
        id: 12,
        country: "Armenia",
        currenciesCode: "AMD",
        currenciesName: "Armenian dram",
        flag: "https://www.countryflags.io/AM/flat/64.png",
    },
    {
        id: 13,
        country: "Aruba",
        currenciesCode: "AWG",
        currenciesName: "Aruban florin",
        flag: "https://www.countryflags.io/AW/flat/64.png",
    },
    {
        id: 14,
        country: "Australia",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/AU/flat/64.png",
    },
    {
        id: 15,
        country: "Austria",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/AT/flat/64.png",
    },
    {
        id: 16,
        country: "Azerbaijan",
        currenciesCode: "AZN",
        currenciesName: "Azerbaijani manat",
        flag: "https://www.countryflags.io/AZ/flat/64.png",
    },
    {
        id: 17,
        country: "Bahamas",
        currenciesCode: "BSD",
        currenciesName: "Bahamian dollar",
        flag: "https://www.countryflags.io/BS/flat/64.png",
    },
    {
        id: 18,
        country: "Bahrain",
        currenciesCode: "BHD",
        currenciesName: "Bahraini dinar",
        flag: "https://www.countryflags.io/BH/flat/64.png",
    },
    {
        id: 19,
        country: "Bangladesh",
        currenciesCode: "BDT",
        currenciesName: "Bangladeshi taka",
        flag: "https://www.countryflags.io/BD/flat/64.png",
    },
    {
        id: 20,
        country: "Barbados",
        currenciesCode: "BBD",
        currenciesName: "Barbadian dollar",
        flag: "https://www.countryflags.io/BB/flat/64.png",
    },
    {
        id: 21,
        country: "Belarus",
        currenciesCode: "BYN",
        currenciesName: "New Belarusian ruble",
        flag: "https://www.countryflags.io/BY/flat/64.png",
    },
    {
        id: 22,
        country: "Belgium",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/BE/flat/64.png",
    },
    {
        id: 23,
        country: "Belize",
        currenciesCode: "BZD",
        currenciesName: "Belize dollar",
        flag: "https://www.countryflags.io/BZ/flat/64.png",
    },
    {
        id: 24,
        country: "Benin",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/BJ/flat/64.png",
    },
    {
        id: 25,
        country: "Bermuda",
        currenciesCode: "BMD",
        currenciesName: "Bermudian dollar",
        flag: "https://www.countryflags.io/BM/flat/64.png",
    },
    {
        id: 26,
        country: "Bhutan",
        currenciesCode: "BTN",
        currenciesName: "Bhutanese ngultrum",
        flag: "https://www.countryflags.io/BT/flat/64.png",
    },
    {
        id: 27,
        country: "Bolivia (Plurinational State of)",
        currenciesCode: "BOB",
        currenciesName: "Bolivian boliviano",
        flag: "https://www.countryflags.io/BO/flat/64.png",
    },
    {
        id: 28,
        country: "Bonaire, Sint Eustatius and Saba",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/BQ/flat/64.png",
    },
    {
        id: 29,
        country: "Bosnia and Herzegovina",
        currenciesCode: "BAM",
        currenciesName: "Bosnia and Herzegovina convertible mark",
        flag: "https://www.countryflags.io/BA/flat/64.png",
    },
    {
        id: 30,
        country: "Botswana",
        currenciesCode: "BWP",
        currenciesName: "Botswana pula",
        flag: "https://www.countryflags.io/BW/flat/64.png",
    },
    {
        id: 31,
        country: "Bouvet Island",
        currenciesCode: "NOK",
        currenciesName: "Norwegian krone",
        flag: "https://www.countryflags.io/BV/flat/64.png",
    },
    {
        id: 32,
        country: "Brazil",
        currenciesCode: "BRL",
        currenciesName: "Brazilian real",
        flag: "https://www.countryflags.io/BR/flat/64.png",
    },
    {
        id: 33,
        country: "British Indian Ocean Territory",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/IO/flat/64.png",
    },
    {
        id: 34,
        country: "United States Minor Outlying Islands",
        currenciesCode: "USD",
        currenciesName: "United States Dollar",
        flag: "https://www.countryflags.io/UM/flat/64.png",
    },
    {
        id: 36,
        country: "Virgin Islands (U.S.)",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/VI/flat/64.png",
    },
    {
        id: 37,
        country: "Brunei Darussalam",
        currenciesCode: "BND",
        currenciesName: "Brunei dollar",
        flag: "https://www.countryflags.io/BN/flat/64.png",
    },
    {
        id: 38,
        country: "Bulgaria",
        currenciesCode: "BGN",
        currenciesName: "Bulgarian lev",
        flag: "https://www.countryflags.io/BG/flat/64.png",
    },
    {
        id: 39,
        country: "Burkina Faso",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/BF/flat/64.png",
    },
    {
        id: 40,
        country: "Burundi",
        currenciesCode: "BIF",
        currenciesName: "Burundian franc",
        flag: "https://www.countryflags.io/BI/flat/64.png",
    },
    {
        id: 41,
        country: "Cambodia",
        currenciesCode: "KHR",
        currenciesName: "Cambodian riel",
        flag: "https://www.countryflags.io/KH/flat/64.png",
    },
    {
        id: 42,
        country: "Cameroon",
        currenciesCode: "XAF",
        currenciesName: "Central African CFA franc",
        flag: "https://www.countryflags.io/CM/flat/64.png",
    },
    {
        id: 43,
        country: "Canada",
        currenciesCode: "CAD",
        currenciesName: "Canadian dollar",
        flag: "https://www.countryflags.io/CA/flat/64.png",
    },
    {
        id: 44,
        country: "Cabo Verde",
        currenciesCode: "CVE",
        currenciesName: "Cape Verdean escudo",
        flag: "https://www.countryflags.io/CV/flat/64.png",
    },
    {
        id: 45,
        country: "Cayman Islands",
        currenciesCode: "KYD",
        currenciesName: "Cayman Islands dollar",
        flag: "https://www.countryflags.io/KY/flat/64.png",
    },
    {
        id: 46,
        country: "Central African Republic",
        currenciesCode: "XAF",
        currenciesName: "Central African CFA franc",
        flag: "https://www.countryflags.io/CF/flat/64.png",
    },
    {
        id: 47,
        country: "Chad",
        currenciesCode: "XAF",
        currenciesName: "Central African CFA franc",
        flag: "https://www.countryflags.io/TD/flat/64.png",
    },
    {
        id: 48,
        country: "Chile",
        currenciesCode: "CLP",
        currenciesName: "Chilean peso",
        flag: "https://www.countryflags.io/CL/flat/64.png",
    },
    {
        id: 49,
        country: "China",
        currenciesCode: "CNY",
        currenciesName: "Chinese yuan",
        flag: "https://www.countryflags.io/CN/flat/64.png",
    },
    {
        id: 50,
        country: "Christmas Island",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/CX/flat/64.png",
    },
    {
        id: 51,
        country: "Cocos (Keeling) Islands",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/CC/flat/64.png",
    },
    {
        id: 52,
        country: "Colombia",
        currenciesCode: "COP",
        currenciesName: "Colombian peso",
        flag: "https://www.countryflags.io/CO/flat/64.png",
    },
    {
        id: 53,
        country: "Comoros",
        currenciesCode: "KMF",
        currenciesName: "Comorian franc",
        flag: "https://www.countryflags.io/KM/flat/64.png",
    },
    {
        id: 54,
        country: "Congo",
        currenciesCode: "XAF",
        currenciesName: "Central African CFA franc",
        flag: "https://www.countryflags.io/CG/flat/64.png",
    },
    {
        id: 55,
        country: "Congo (Democratic Republic of the)",
        currenciesCode: "CDF",
        currenciesName: "Congolese franc",
        flag: "https://www.countryflags.io/CD/flat/64.png",
    },
    {
        id: 56,
        country: "Cook Islands",
        currenciesCode: "NZD",
        currenciesName: "New Zealand dollar",
        flag: "https://www.countryflags.io/CK/flat/64.png",
    },
    {
        id: 57,
        country: "Costa Rica",
        currenciesCode: "CRC",
        currenciesName: "Costa Rican colón",
        flag: "https://www.countryflags.io/CR/flat/64.png",
    },
    {
        id: 58,
        country: "Croatia",
        currenciesCode: "HRK",
        currenciesName: "Croatian kuna",
        flag: "https://www.countryflags.io/HR/flat/64.png",
    },
    {
        id: 59,
        country: "Cuba",
        currenciesCode: "CUC",
        currenciesName: "Cuban convertible peso",
        flag: "https://www.countryflags.io/CU/flat/64.png",
    },
    {
        id: 60,
        country: "Curaçao",
        currenciesCode: "ANG",
        currenciesName: "Netherlands Antillean guilder",
        flag: "https://www.countryflags.io/CW/flat/64.png",
    },
    {
        id: 61,
        country: "Cyprus",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/CY/flat/64.png",
    },
    {
        id: 62,
        country: "Czech Republic",
        currenciesCode: "CZK",
        currenciesName: "Czech koruna",
        flag: "https://www.countryflags.io/CZ/flat/64.png",
    },
    {
        id: 63,
        country: "Denmark",
        currenciesCode: "DKK",
        currenciesName: "Danish krone",
        flag: "https://www.countryflags.io/DK/flat/64.png",
    },
    {
        id: 64,
        country: "Djibouti",
        currenciesCode: "DJF",
        currenciesName: "Djiboutian franc",
        flag: "https://www.countryflags.io/DJ/flat/64.png",
    },
    {
        id: 65,
        country: "Dominica",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/DM/flat/64.png",
    },
    {
        id: 66,
        country: "Dominican Republic",
        currenciesCode: "DOP",
        currenciesName: "Dominican peso",
        flag: "https://www.countryflags.io/DO/flat/64.png",
    },
    {
        id: 67,
        country: "Ecuador",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/EC/flat/64.png",
    },
    {
        id: 68,
        country: "Egypt",
        currenciesCode: "EGP",
        currenciesName: "Egyptian pound",
        flag: "https://www.countryflags.io/EG/flat/64.png",
    },
    {
        id: 69,
        country: "El Salvador",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/SV/flat/64.png",
    },
    {
        id: 70,
        country: "Equatorial Guinea",
        currenciesCode: "XAF",
        currenciesName: "Central African CFA franc",
        flag: "https://www.countryflags.io/GQ/flat/64.png",
    },
    {
        id: 71,
        country: "Eritrea",
        currenciesCode: "ERN",
        currenciesName: "Eritrean nakfa",
        flag: "https://www.countryflags.io/ER/flat/64.png",
    },
    {
        id: 72,
        country: "Estonia",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/EE/flat/64.png",
    },
    {
        id: 73,
        country: "Ethiopia",
        currenciesCode: "ETB",
        currenciesName: "Ethiopian birr",
        flag: "https://www.countryflags.io/ET/flat/64.png",
    },
    {
        id: 74,
        country: "Falkland Islands (Malvinas)",
        currenciesCode: "FKP",
        currenciesName: "Falkland Islands pound",
        flag: "https://www.countryflags.io/FK/flat/64.png",
    },
    {
        id: 75,
        country: "Faroe Islands",
        currenciesCode: "DKK",
        currenciesName: "Danish krone",
        flag: "https://www.countryflags.io/FO/flat/64.png",
    },
    {
        id: 76,
        country: "Fiji",
        currenciesCode: "FJD",
        currenciesName: "Fijian dollar",
        flag: "https://www.countryflags.io/FJ/flat/64.png",
    },
    {
        id: 77,
        country: "Finland",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/FI/flat/64.png",
    },
    {
        id: 78,
        country: "France",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/FR/flat/64.png",
    },
    {
        id: 79,
        country: "French Guiana",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/GF/flat/64.png",
    },
    {
        id: 80,
        country: "French Polynesia",
        currenciesCode: "XPF",
        currenciesName: "CFP franc",
        flag: "https://www.countryflags.io/PF/flat/64.png",
    },
    {
        id: 81,
        country: "French Southern Territories",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/TF/flat/64.png",
    },
    {
        id: 82,
        country: "Gabon",
        currenciesCode: "XAF",
        currenciesName: "Central African CFA franc",
        flag: "https://www.countryflags.io/GA/flat/64.png",
    },
    {
        id: 83,
        country: "Gambia",
        currenciesCode: "GMD",
        currenciesName: "Gambian dalasi",
        flag: "https://www.countryflags.io/GM/flat/64.png",
    },
    {
        id: 84,
        country: "Georgia",
        currenciesCode: "GEL",
        currenciesName: "Georgian Lari",
        flag: "https://www.countryflags.io/GE/flat/64.png",
    },
    {
        id: 85,
        country: "Germany",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/DE/flat/64.png",
    },
    {
        id: 86,
        country: "Ghana",
        currenciesCode: "GHS",
        currenciesName: "Ghanaian cedi",
        flag: "https://www.countryflags.io/GH/flat/64.png",
    },
    {
        id: 87,
        country: "Gibraltar",
        currenciesCode: "GIP",
        currenciesName: "Gibraltar pound",
        flag: "https://www.countryflags.io/GI/flat/64.png",
    },
    {
        id: 88,
        country: "Greece",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/GR/flat/64.png",
    },
    {
        id: 89,
        country: "Greenland",
        currenciesCode: "DKK",
        currenciesName: "Danish krone",
        flag: "https://www.countryflags.io/GL/flat/64.png",
    },
    {
        id: 90,
        country: "Grenada",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/GD/flat/64.png",
    },
    {
        id: 91,
        country: "Guadeloupe",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/GP/flat/64.png",
    },
    {
        id: 92,
        country: "Guam",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/GU/flat/64.png",
    },
    {
        id: 93,
        country: "Guatemala",
        currenciesCode: "GTQ",
        currenciesName: "Guatemalan quetzal",
        flag: "https://www.countryflags.io/GT/flat/64.png",
    },
    {
        id: 94,
        country: "Guernsey",
        currenciesCode: "GBP",
        currenciesName: "British pound",
        flag: "https://www.countryflags.io/GG/flat/64.png",
    },
    {
        id: 95,
        country: "Guinea",
        currenciesCode: "GNF",
        currenciesName: "Guinean franc",
        flag: "https://www.countryflags.io/GN/flat/64.png",
    },
    {
        id: 96,
        country: "Guinea-Bissau",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/GW/flat/64.png",
    },
    {
        id: 97,
        country: "Guyana",
        currenciesCode: "GYD",
        currenciesName: "Guyanese dollar",
        flag: "https://www.countryflags.io/GY/flat/64.png",
    },
    {
        id: 98,
        country: "Haiti",
        currenciesCode: "HTG",
        currenciesName: "Haitian gourde",
        flag: "https://www.countryflags.io/HT/flat/64.png",
    },
    {
        id: 99,
        country: "Heard Island and McDonald Islands",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/HM/flat/64.png",
    },
    {
        id: 100,
        country: "Holy See",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/VA/flat/64.png",
    },
    {
        id: 101,
        country: "Honduras",
        currenciesCode: "HNL",
        currenciesName: "Honduran lempira",
        flag: "https://www.countryflags.io/HN/flat/64.png",
    },
    {
        id: 102,
        country: "Hong Kong",
        currenciesCode: "HKD",
        currenciesName: "Hong Kong dollar",
        flag: "https://www.countryflags.io/HK/flat/64.png",
    },
    {
        id: 103,
        country: "Hungary",
        currenciesCode: "HUF",
        currenciesName: "Hungarian forint",
        flag: "https://www.countryflags.io/HU/flat/64.png",
    },
    {
        id: 104,
        country: "Iceland",
        currenciesCode: "ISK",
        currenciesName: "Icelandic króna",
        flag: "https://www.countryflags.io/IS/flat/64.png",
    },
    {
        id: 105,
        country: "India",
        currenciesCode: "INR",
        currenciesName: "Indian rupee",
        flag: "https://www.countryflags.io/IN/flat/64.png",
    },
    {
        id: 106,
        country: "Indonesia",
        currenciesCode: "IDR",
        currenciesName: "Indonesian rupiah",
        flag: "https://www.countryflags.io/ID/flat/64.png",
    },
    {
        id: 107,
        country: "Côte d'Ivoire",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/CI/flat/64.png",
    },
    {
        id: 108,
        country: "Iran (Islamic Republic of)",
        currenciesCode: "IRR",
        currenciesName: "Iranian rial",
        flag: "https://www.countryflags.io/IR/flat/64.png",
    },
    {
        id: 109,
        country: "Iraq",
        currenciesCode: "IQD",
        currenciesName: "Iraqi dinar",
        flag: "https://www.countryflags.io/IQ/flat/64.png",
    },
    {
        id: 110,
        country: "Ireland",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/IE/flat/64.png",
    },
    {
        id: 111,
        country: "Isle of Man",
        currenciesCode: "GBP",
        currenciesName: "British pound",
        flag: "https://www.countryflags.io/IM/flat/64.png",
    },
    {
        id: 112,
        country: "Israel",
        currenciesCode: "ILS",
        currenciesName: "Israeli new shekel",
        flag: "https://www.countryflags.io/IL/flat/64.png",
    },
    {
        id: 113,
        country: "Italy",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/IT/flat/64.png",
    },
    {
        id: 114,
        country: "Jamaica",
        currenciesCode: "JMD",
        currenciesName: "Jamaican dollar",
        flag: "https://www.countryflags.io/JM/flat/64.png",
    },
    {
        id: 115,
        country: "Japan",
        currenciesCode: "JPY",
        currenciesName: "Japanese yen",
        flag: "https://www.countryflags.io/JP/flat/64.png",
    },
    {
        id: 116,
        country: "Jersey",
        currenciesCode: "GBP",
        currenciesName: "British pound",
        flag: "https://www.countryflags.io/JE/flat/64.png",
    },
    {
        id: 117,
        country: "Jordan",
        currenciesCode: "JOD",
        currenciesName: "Jordanian dinar",
        flag: "https://www.countryflags.io/JO/flat/64.png",
    },
    {
        id: 118,
        country: "Kazakhstan",
        currenciesCode: "KZT",
        currenciesName: "Kazakhstani tenge",
        flag: "https://www.countryflags.io/KZ/flat/64.png",
    },
    {
        id: 119,
        country: "Kenya",
        currenciesCode: "KES",
        currenciesName: "Kenyan shilling",
        flag: "https://www.countryflags.io/KE/flat/64.png",
    },
    {
        id: 120,
        country: "Kiribati",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/KI/flat/64.png",
    },
    {
        id: 121,
        country: "Kuwait",
        currenciesCode: "KWD",
        currenciesName: "Kuwaiti dinar",
        flag: "https://www.countryflags.io/KW/flat/64.png",
    },
    {
        id: 122,
        country: "Kyrgyzstan",
        currenciesCode: "KGS",
        currenciesName: "Kyrgyzstani som",
        flag: "https://www.countryflags.io/KG/flat/64.png",
    },
    {
        id: 123,
        country: "Lao People's Democratic Republic",
        currenciesCode: "LAK",
        currenciesName: "Lao kip",
        flag: "https://www.countryflags.io/LA/flat/64.png",
    },
    {
        id: 124,
        country: "Latvia",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/LV/flat/64.png",
    },
    {
        id: 125,
        country: "Lebanon",
        currenciesCode: "LBP",
        currenciesName: "Lebanese pound",
        flag: "https://www.countryflags.io/LB/flat/64.png",
    },
    {
        id: 126,
        country: "Lesotho",
        currenciesCode: "LSL",
        currenciesName: "Lesotho loti",
        flag: "https://www.countryflags.io/LS/flat/64.png",
    },
    {
        id: 127,
        country: "Liberia",
        currenciesCode: "LRD",
        currenciesName: "Liberian dollar",
        flag: "https://www.countryflags.io/LR/flat/64.png",
    },
    {
        id: 128,
        country: "Libya",
        currenciesCode: "LYD",
        currenciesName: "Libyan dinar",
        flag: "https://www.countryflags.io/LY/flat/64.png",
    },
    {
        id: 129,
        country: "Liechtenstein",
        currenciesCode: "CHF",
        currenciesName: "Swiss franc",
        flag: "https://www.countryflags.io/LI/flat/64.png",
    },
    {
        id: 130,
        country: "Lithuania",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/LT/flat/64.png",
    },
    {
        id: 131,
        country: "Luxembourg",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/LU/flat/64.png",
    },
    {
        id: 132,
        country: "Macao",
        currenciesCode: "MOP",
        currenciesName: "Macanese pataca",
        flag: "https://www.countryflags.io/MO/flat/64.png",
    },
    {
        id: 133,
        country: "Macedonia (the former Yugoslav Republic of)",
        currenciesCode: "MKD",
        currenciesName: "Macedonian denar",
        flag: "https://www.countryflags.io/MK/flat/64.png",
    },
    {
        id: 134,
        country: "Madagascar",
        currenciesCode: "MGA",
        currenciesName: "Malagasy ariary",
        flag: "https://www.countryflags.io/MG/flat/64.png",
    },
    {
        id: 135,
        country: "Malawi",
        currenciesCode: "MWK",
        currenciesName: "Malawian kwacha",
        flag: "https://www.countryflags.io/MW/flat/64.png",
    },
    {
        id: 136,
        country: "Malaysia",
        currenciesCode: "MYR",
        currenciesName: "Malaysian ringgit",
        flag: "https://www.countryflags.io/MY/flat/64.png",
    },
    {
        id: 137,
        country: "Maldives",
        currenciesCode: "MVR",
        currenciesName: "Maldivian rufiyaa",
        flag: "https://www.countryflags.io/MV/flat/64.png",
    },
    {
        id: 138,
        country: "Mali",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/ML/flat/64.png",
    },
    {
        id: 139,
        country: "Malta",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/MT/flat/64.png",
    },
    {
        id: 140,
        country: "Marshall Islands",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/MH/flat/64.png",
    },
    {
        id: 141,
        country: "Martinique",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/MQ/flat/64.png",
    },
    {
        id: 142,
        country: "Mauritania",
        currenciesCode: "MRO",
        currenciesName: "Mauritanian ouguiya",
        flag: "https://www.countryflags.io/MR/flat/64.png",
    },
    {
        id: 143,
        country: "Mauritius",
        currenciesCode: "MUR",
        currenciesName: "Mauritian rupee",
        flag: "https://www.countryflags.io/MU/flat/64.png",
    },
    {
        id: 144,
        country: "Mayotte",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/YT/flat/64.png",
    },
    {
        id: 145,
        country: "Mexico",
        currenciesCode: "MXN",
        currenciesName: "Mexican peso",
        flag: "https://www.countryflags.io/MX/flat/64.png",
    },
    {
        id: 147,
        country: "Moldova (Republic of)",
        currenciesCode: "MDL",
        currenciesName: "Moldovan leu",
        flag: "https://www.countryflags.io/MD/flat/64.png",
    },
    {
        id: 148,
        country: "Monaco",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/MC/flat/64.png",
    },
    {
        id: 149,
        country: "Mongolia",
        currenciesCode: "MNT",
        currenciesName: "Mongolian tögrög",
        flag: "https://www.countryflags.io/MN/flat/64.png",
    },
    {
        id: 150,
        country: "Montenegro",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/ME/flat/64.png",
    },
    {
        id: 151,
        country: "Montserrat",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/MS/flat/64.png",
    },
    {
        id: 152,
        country: "Morocco",
        currenciesCode: "MAD",
        currenciesName: "Moroccan dirham",
        flag: "https://www.countryflags.io/MA/flat/64.png",
    },
    {
        id: 153,
        country: "Mozambique",
        currenciesCode: "MZN",
        currenciesName: "Mozambican metical",
        flag: "https://www.countryflags.io/MZ/flat/64.png",
    },
    {
        id: 154,
        country: "Myanmar",
        currenciesCode: "MMK",
        currenciesName: "Burmese kyat",
        flag: "https://www.countryflags.io/MM/flat/64.png",
    },
    {
        id: 155,
        country: "Namibia",
        currenciesCode: "NAD",
        currenciesName: "Namibian dollar",
        flag: "https://www.countryflags.io/NA/flat/64.png",
    },
    {
        id: 156,
        country: "Nauru",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/NR/flat/64.png",
    },
    {
        id: 157,
        country: "Nepal",
        currenciesCode: "NPR",
        currenciesName: "Nepalese rupee",
        flag: "https://www.countryflags.io/NP/flat/64.png",
    },
    {
        id: 158,
        country: "Netherlands",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/NL/flat/64.png",
    },
    {
        id: 159,
        country: "New Caledonia",
        currenciesCode: "XPF",
        currenciesName: "CFP franc",
        flag: "https://www.countryflags.io/NC/flat/64.png",
    },
    {
        id: 160,
        country: "New Zealand",
        currenciesCode: "NZD",
        currenciesName: "New Zealand dollar",
        flag: "https://www.countryflags.io/NZ/flat/64.png",
    },
    {
        id: 161,
        country: "Nicaragua",
        currenciesCode: "NIO",
        currenciesName: "Nicaraguan córdoba",
        flag: "https://www.countryflags.io/NI/flat/64.png",
    },
    {
        id: 162,
        country: "Niger",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/NE/flat/64.png",
    },
    {
        id: 163,
        country: "Nigeria",
        currenciesCode: "NGN",
        currenciesName: "Nigerian naira",
        flag: "https://www.countryflags.io/NG/flat/64.png",
    },
    {
        id: 164,
        country: "Niue",
        currenciesCode: "NZD",
        currenciesName: "New Zealand dollar",
        flag: "https://www.countryflags.io/NU/flat/64.png",
    },
    {
        id: 165,
        country: "Norfolk Island",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/NF/flat/64.png",
    },
    {
        id: 166,
        country: "Korea (Democratic People's Republic of)",
        currenciesCode: "KPW",
        currenciesName: "North Korean won",
        flag: "https://www.countryflags.io/KP/flat/64.png",
    },
    {
        id: 167,
        country: "Northern Mariana Islands",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/MP/flat/64.png",
    },
    {
        id: 168,
        country: "Norway",
        currenciesCode: "NOK",
        currenciesName: "Norwegian krone",
        flag: "https://www.countryflags.io/NO/flat/64.png",
    },
    {
        id: 169,
        country: "Oman",
        currenciesCode: "OMR",
        currenciesName: "Omani rial",
        flag: "https://www.countryflags.io/OM/flat/64.png",
    },
    {
        id: 170,
        country: "Pakistan",
        currenciesCode: "PKR",
        currenciesName: "Pakistani rupee",
        flag: "https://www.countryflags.io/PK/flat/64.png",
    },
    {
        id: 172,
        country: "Palestine, State of",
        currenciesCode: "ILS",
        currenciesName: "Israeli new sheqel",
        flag: "https://www.countryflags.io/PS/flat/64.png",
    },
    {
        id: 173,
        country: "Panama",
        currenciesCode: "PAB",
        currenciesName: "Panamanian balboa",
        flag: "https://www.countryflags.io/PA/flat/64.png",
    },
    {
        id: 174,
        country: "Papua New Guinea",
        currenciesCode: "PGK",
        currenciesName: "Papua New Guinean kina",
        flag: "https://www.countryflags.io/PG/flat/64.png",
    },
    {
        id: 175,
        country: "Paraguay",
        currenciesCode: "PYG",
        currenciesName: "Paraguayan guaraní",
        flag: "https://www.countryflags.io/PY/flat/64.png",
    },
    {
        id: 176,
        country: "Peru",
        currenciesCode: "PEN",
        currenciesName: "Peruvian sol",
        flag: "https://www.countryflags.io/PE/flat/64.png",
    },
    {
        id: 177,
        country: "Philippines",
        currenciesCode: "PHP",
        currenciesName: "Philippine peso",
        flag: "https://www.countryflags.io/PH/flat/64.png",
    },
    {
        id: 178,
        country: "Pitcairn",
        currenciesCode: "NZD",
        currenciesName: "New Zealand dollar",
        flag: "https://www.countryflags.io/PN/flat/64.png",
    },
    {
        id: 179,
        country: "Poland",
        currenciesCode: "PLN",
        currenciesName: "Polish złoty",
        flag: "https://www.countryflags.io/PL/flat/64.png",
    },
    {
        id: 180,
        country: "Portugal",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/PT/flat/64.png",
    },
    {
        id: 181,
        country: "Puerto Rico",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/PR/flat/64.png",
    },
    {
        id: 182,
        country: "Qatar",
        currenciesCode: "QAR",
        currenciesName: "Qatari riyal",
        flag: "https://www.countryflags.io/QA/flat/64.png",
    },
    {
        id: 183,
        country: "Republic of Kosovo",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/XK/flat/64.png",
    },
    {
        id: 184,
        country: "Réunion",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/RE/flat/64.png",
    },
    {
        id: 185,
        country: "Romania",
        currenciesCode: "RON",
        currenciesName: "Romanian leu",
        flag: "https://www.countryflags.io/RO/flat/64.png",
    },
    {
        id: 186,
        country: "Russian Federation",
        currenciesCode: "RUB",
        currenciesName: "Russian ruble",
        flag: "https://www.countryflags.io/RU/flat/64.png",
    },
    {
        id: 187,
        country: "Rwanda",
        currenciesCode: "RWF",
        currenciesName: "Rwandan franc",
        flag: "https://www.countryflags.io/RW/flat/64.png",
    },
    {
        id: 188,
        country: "Saint Barthélemy",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/BL/flat/64.png",
    },
    {
        id: 189,
        country: "Saint Helena, Ascension and Tristan da Cunha",
        currenciesCode: "SHP",
        currenciesName: "Saint Helena pound",
        flag: "https://www.countryflags.io/SH/flat/64.png",
    },
    {
        id: 190,
        country: "Saint Kitts and Nevis",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/KN/flat/64.png",
    },
    {
        id: 191,
        country: "Saint Lucia",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/LC/flat/64.png",
    },
    {
        id: 192,
        country: "Saint Martin (French part)",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/MF/flat/64.png",
    },
    {
        id: 193,
        country: "Saint Pierre and Miquelon",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/PM/flat/64.png",
    },
    {
        id: 194,
        country: "Saint Vincent and the Grenadines",
        currenciesCode: "XCD",
        currenciesName: "East Caribbean dollar",
        flag: "https://www.countryflags.io/VC/flat/64.png",
    },
    {
        id: 195,
        country: "Samoa",
        currenciesCode: "WST",
        currenciesName: "Samoan tālā",
        flag: "https://www.countryflags.io/WS/flat/64.png",
    },
    {
        id: 196,
        country: "San Marino",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/SM/flat/64.png",
    },
    {
        id: 197,
        country: "Sao Tome and Principe",
        currenciesCode: "STD",
        currenciesName: "São Tomé and Príncipe dobra",
        flag: "https://www.countryflags.io/ST/flat/64.png",
    },
    {
        id: 198,
        country: "Saudi Arabia",
        currenciesCode: "SAR",
        currenciesName: "Saudi riyal",
        flag: "https://www.countryflags.io/SA/flat/64.png",
    },
    {
        id: 199,
        country: "Senegal",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/SN/flat/64.png",
    },
    {
        id: 200,
        country: "Serbia",
        currenciesCode: "RSD",
        currenciesName: "Serbian dinar",
        flag: "https://www.countryflags.io/RS/flat/64.png",
    },
    {
        id: 201,
        country: "Seychelles",
        currenciesCode: "SCR",
        currenciesName: "Seychellois rupee",
        flag: "https://www.countryflags.io/SC/flat/64.png",
    },
    {
        id: 202,
        country: "Sierra Leone",
        currenciesCode: "SLL",
        currenciesName: "Sierra Leonean leone",
        flag: "https://www.countryflags.io/SL/flat/64.png",
    },
    {
        id: 203,
        country: "Singapore",
        currenciesCode: "BND",
        currenciesName: "Brunei dollar",
        flag: "https://www.countryflags.io/SG/flat/64.png",
    },
    {
        id: 204,
        country: "Sint Maarten (Dutch part)",
        currenciesCode: "ANG",
        currenciesName: "Netherlands Antillean guilder",
        flag: "https://www.countryflags.io/SX/flat/64.png",
    },
    {
        id: 205,
        country: "Slovakia",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/SK/flat/64.png",
    },
    {
        id: 206,
        country: "Slovenia",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/SI/flat/64.png",
    },
    {
        id: 207,
        country: "Solomon Islands",
        currenciesCode: "SBD",
        currenciesName: "Solomon Islands dollar",
        flag: "https://www.countryflags.io/SB/flat/64.png",
    },
    {
        id: 208,
        country: "Somalia",
        currenciesCode: "SOS",
        currenciesName: "Somali shilling",
        flag: "https://www.countryflags.io/SO/flat/64.png",
    },
    {
        id: 209,
        country: "South Africa",
        currenciesCode: "ZAR",
        currenciesName: "South African rand",
        flag: "https://www.countryflags.io/ZA/flat/64.png",
    },
    {
        id: 210,
        country: "South Georgia and the South Sandwich Islands",
        currenciesCode: "GBP",
        currenciesName: "British pound",
        flag: "https://www.countryflags.io/GS/flat/64.png",
    },
    {
        id: 211,
        country: "Korea (Republic of)",
        currenciesCode: "KRW",
        currenciesName: "South Korean won",
        flag: "https://www.countryflags.io/KR/flat/64.png",
    },
    {
        id: 212,
        country: "South Sudan",
        currenciesCode: "SSP",
        currenciesName: "South Sudanese pound",
        flag: "https://www.countryflags.io/SS/flat/64.png",
    },
    {
        id: 213,
        country: "Spain",
        currenciesCode: "EUR",
        currenciesName: "Euro",
        flag: "https://www.countryflags.io/ES/flat/64.png",
    },
    {
        id: 214,
        country: "Sri Lanka",
        currenciesCode: "LKR",
        currenciesName: "Sri Lankan rupee",
        flag: "https://www.countryflags.io/LK/flat/64.png",
    },
    {
        id: 215,
        country: "Sudan",
        currenciesCode: "SDG",
        currenciesName: "Sudanese pound",
        flag: "https://www.countryflags.io/SD/flat/64.png",
    },
    {
        id: 216,
        country: "Suriname",
        currenciesCode: "SRD",
        currenciesName: "Surinamese dollar",
        flag: "https://www.countryflags.io/SR/flat/64.png",
    },
    {
        id: 217,
        country: "Svalbard and Jan Mayen",
        currenciesCode: "NOK",
        currenciesName: "Norwegian krone",
        flag: "https://www.countryflags.io/SJ/flat/64.png",
    },
    {
        id: 218,
        country: "Swaziland",
        currenciesCode: "SZL",
        currenciesName: "Swazi lilangeni",
        flag: "https://www.countryflags.io/SZ/flat/64.png",
    },
    {
        id: 219,
        country: "Sweden",
        currenciesCode: "SEK",
        currenciesName: "Swedish krona",
        flag: "https://www.countryflags.io/SE/flat/64.png",
    },
    {
        id: 220,
        country: "Switzerland",
        currenciesCode: "CHF",
        currenciesName: "Swiss franc",
        flag: "https://www.countryflags.io/CH/flat/64.png",
    },
    {
        id: 221,
        country: "Syrian Arab Republic",
        currenciesCode: "SYP",
        currenciesName: "Syrian pound",
        flag: "https://www.countryflags.io/SY/flat/64.png",
    },
    {
        id: 222,
        country: "Taiwan",
        currenciesCode: "TWD",
        currenciesName: "New Taiwan dollar",
        flag: "https://www.countryflags.io/TW/flat/64.png",
    },
    {
        id: 223,
        country: "Tajikistan",
        currenciesCode: "TJS",
        currenciesName: "Tajikistani somoni",
        flag: "https://www.countryflags.io/TJ/flat/64.png",
    },
    {
        id: 224,
        country: "Tanzania, United Republic of",
        currenciesCode: "TZS",
        currenciesName: "Tanzanian shilling",
        flag: "https://www.countryflags.io/TZ/flat/64.png",
    },
    {
        id: 225,
        country: "Thailand",
        currenciesCode: "THB",
        currenciesName: "Thai baht",
        flag: "https://www.countryflags.io/TH/flat/64.png",
    },
    {
        id: 226,
        country: "Timor-Leste",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/TL/flat/64.png",
    },
    {
        id: 227,
        country: "Togo",
        currenciesCode: "XOF",
        currenciesName: "West African CFA franc",
        flag: "https://www.countryflags.io/TG/flat/64.png",
    },
    {
        id: 228,
        country: "Tokelau",
        currenciesCode: "NZD",
        currenciesName: "New Zealand dollar",
        flag: "https://www.countryflags.io/TK/flat/64.png",
    },
    {
        id: 229,
        country: "Tonga",
        currenciesCode: "TOP",
        currenciesName: "Tongan paʻanga",
        flag: "https://www.countryflags.io/TO/flat/64.png",
    },
    {
        id: 230,
        country: "Trinidad and Tobago",
        currenciesCode: "TTD",
        currenciesName: "Trinidad and Tobago dollar",
        flag: "https://www.countryflags.io/TT/flat/64.png",
    },
    {
        id: 231,
        country: "Tunisia",
        currenciesCode: "TND",
        currenciesName: "Tunisian dinar",
        flag: "https://www.countryflags.io/TN/flat/64.png",
    },
    {
        id: 232,
        country: "Turkey",
        currenciesCode: "TRY",
        currenciesName: "Turkish lira",
        flag: "https://www.countryflags.io/TR/flat/64.png",
    },
    {
        id: 233,
        country: "Turkmenistan",
        currenciesCode: "TMT",
        currenciesName: "Turkmenistan manat",
        flag: "https://www.countryflags.io/TM/flat/64.png",
    },
    {
        id: 234,
        country: "Turks and Caicos Islands",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/TC/flat/64.png",
    },
    {
        id: 235,
        country: "Tuvalu",
        currenciesCode: "AUD",
        currenciesName: "Australian dollar",
        flag: "https://www.countryflags.io/TV/flat/64.png",
    },
    {
        id: 236,
        country: "Uganda",
        currenciesCode: "UGX",
        currenciesName: "Ugandan shilling",
        flag: "https://www.countryflags.io/UG/flat/64.png",
    },
    {
        id: 237,
        country: "Ukraine",
        currenciesCode: "UAH",
        currenciesName: "Ukrainian hryvnia",
        flag: "https://www.countryflags.io/UA/flat/64.png",
    },
    {
        id: 238,
        country: "United Arab Emirates",
        currenciesCode: "AED",
        currenciesName: "United Arab Emirates dirham",
        flag: "https://www.countryflags.io/AE/flat/64.png",
    },
    {
        id: 239,
        country: "United Kingdom of Great Britain and Northern Ireland",
        currenciesCode: "GBP",
        currenciesName: "British pound",
        flag: "https://www.countryflags.io/GB/flat/64.png",
    },
    {
        id: 240,
        country: "United States of America",
        currenciesCode: "USD",
        currenciesName: "United States dollar",
        flag: "https://www.countryflags.io/US/flat/64.png",
    },
    {
        id: 241,
        country: "Uruguay",
        currenciesCode: "UYU",
        currenciesName: "Uruguayan peso",
        flag: "https://www.countryflags.io/UY/flat/64.png",
    },
    {
        id: 242,
        country: "Uzbekistan",
        currenciesCode: "UZS",
        currenciesName: "Uzbekistani so'm",
        flag: "https://www.countryflags.io/UZ/flat/64.png",
    },
    {
        id: 243,
        country: "Vanuatu",
        currenciesCode: "VUV",
        currenciesName: "Vanuatu vatu",
        flag: "https://www.countryflags.io/VU/flat/64.png",
    },
    {
        id: 244,
        country: "Venezuela (Bolivarian Republic of)",
        currenciesCode: "VEF",
        currenciesName: "Venezuelan bolívar",
        flag: "https://www.countryflags.io/VE/flat/64.png",
    },
    {
        id: 245,
        country: "Viet Nam",
        currenciesCode: "VND",
        currenciesName: "Vietnamese đồng",
        flag: "https://www.countryflags.io/VN/flat/64.png",
    },
    {
        id: 246,
        country: "Wallis and Futuna",
        currenciesCode: "XPF",
        currenciesName: "CFP franc",
        flag: "https://www.countryflags.io/WF/flat/64.png",
    },
    {
        id: 247,
        country: "Western Sahara",
        currenciesCode: "MAD",
        currenciesName: "Moroccan dirham",
        flag: "https://www.countryflags.io/EH/flat/64.png",
    },
    {
        id: 248,
        country: "Yemen",
        currenciesCode: "YER",
        currenciesName: "Yemeni rial",
        flag: "https://www.countryflags.io/YE/flat/64.png",
    },
    {
        id: 249,
        country: "Zambia",
        currenciesCode: "ZMW",
        currenciesName: "Zambian kwacha",
        flag: "https://www.countryflags.io/ZM/flat/64.png",
    },
    {
        id: 250,
        country: "Zimbabwe",
        currenciesCode: "BWP",
        currenciesName: "Botswana pula",
        flag: "https://www.countryflags.io/ZW/flat/64.png",
    },
];
